version: 2
registries:
  porting-assistant-nuget:
    type: nuget-feed
    url: https://s3-us-west-2.amazonaws.com/aws.portingassistant.dotnet.download/nuget/index.json
  nuget-org:
    type: nuget-feed
    url: https://api.nuget.org/v3/index.json
updates:
  - package-ecosystem: "nuget"
    directory: "/src/CTA.FeatureDetection"
    registries:
      - porting-assistant-nuget
      - nuget-org
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/src/CTA.FeatureDetection.AuthType"
    registries:
      - porting-assistant-nuget
      - nuget-org
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/src/CTA.FeatureDetection.Common"
    registries:
      - porting-assistant-nuget
      - nuget-org
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/src/CTA.FeatureDetection.Load"
    registries:
      - porting-assistant-nuget
      - nuget-org
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/src/CTA.FeatureDetection.ProjectType"
    registries:
      - porting-assistant-nuget
      - nuget-org
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/tst/CTA.FeatureDetection.Tests"
    registries:
      - porting-assistant-nuget
      - nuget-org
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/src/CTA.Rules.Actions"
    registries:
      - porting-assistant-nuget
      - nuget-org
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/src/CTA.Rules.Analysis"
    registries:
      - porting-assistant-nuget
      - nuget-org
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/src/CTA.Rules.Common"
    registries:
      - porting-assistant-nuget
      - nuget-org
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/src/CTA.Rules.Config"
    registries:
      - porting-assistant-nuget
      - nuget-org
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/src/CTA.Rules.Metrics"
    registries:
      - porting-assistant-nuget
      - nuget-org
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/src/CTA.Rules.Models"
    registries:
      - porting-assistant-nuget
      - nuget-org
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/src/CTA.Rules.PortCore"
    registries:
      - porting-assistant-nuget
      - nuget-org
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/src/CTA.Rules.ProjectFile"
    registries:
      - porting-assistant-nuget
      - nuget-org
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/src/CTA.Rules.RuleFiles"
    registries:
      - porting-assistant-nuget
      - nuget-org
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/tst/CTA.Rules.Test"
    registries:
      - porting-assistant-nuget
      - nuget-org
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/src/CTA.Rules.Update"
    registries:
      - porting-assistant-nuget
      - nuget-org
    schedule:
      interval: "weekly"
